audio_group_load(audiogroup_music)
audio_group_load(audiogroup_default)
audio_falloff_set_model(audio_falloff_exponent_distance)
max_distance_to_be_heard = 300
start_dropping_off_at = 50
multiplier = 10