ID = obj_player1
image_blend = choose(c_red, c_green)
image_xscale = ID.xscale
image_yscale = ID.yscale
sprite_index = ID.sprite_index
image_index = ID.image_index
image_speed = 0
alpha = 1
depth = -125
alarm[0] = 5