draw_set_alpha(fade)
draw_set_color(c_white)
draw_sprite_ext(spr_knife, -1, 12, 20, 0.5, 0.5, 0, (global.item == 0 ? c_white : c_black), fade)
draw_sprite(spr_inv, -1, 0, 0)
draw_sprite_ext(spr_playerbomb, -1, 67, 18, 0.5, 0.5, 0, (global.item == 1 ? c_white : c_black), fade)
draw_sprite(spr_inv, -1, 40, 0)
draw_set_color(c_red)
draw_sprite(spr_inv, -1, 0 + (40 * global.item), 0)
draw_set_alpha(1)