global.visiblecollisions = 0
global.fill = 0
global.panic = 0
global.saveroom = ds_list_create()
global.baddieroom = ds_list_create()
global.doorrestartto = "A"
global.roomrestartto = 0
rage = 0
flash = 0
momentum = 0
exitlevel = 0
charge = 0
shadowalpha = 0 // this isnt the shadow BELOW the player, its the one thats ABOVE, used for when exiting doors
hallway = 0
hallwaydir = 1
hitbuffer = 0
coop = 0
xscale = 1
yscale = 1
rot = 1
alpha = 1
state = states.normal
movespeed = 0
resolution = 0
use_controls = 1
targetDoor = "A"
runjump = 0
machafterimage = 10
slamafterimage = 5
depth = -999
scr_initinput()
scr_collision_init()