draw_set_alpha(1)
draw_set_color(c_white)
draw_set_halign(fa_center)
draw_set_valign(fa_bottom)
draw_set_font(global.defaultfont)
draw_sprite_ext(hudspr, -1, 105, hudy + 2, 1, 1, 0, c_black, 0.4)
draw_sprite(hudspr, -1, 100, hudy)
draw_text_transformed(100, hudy + 75, global.collect, 1, 1, 0)
draw_set_alpha(1)
